<a href="https://colab.research.google.com/github/andreviniciusmb/ia_ic/blob/main/Classificacao_IC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício

No exemplo acima, na base de dados Iris, apenas as duas primeiras características foram exploradas. Você deve:

- Explorar as demais características e mostrar resultados comparativos.

- Testar com outro algoritmo de classificação e discutir os resultados.

In [40]:
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.metrics import plot_confusion_matrix,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split

# Modeling
from sklearn.neighbors import KNeighborsClassifier

import warnings
warnings.filterwarnings('ignore')

In [27]:
iris = datasets.load_iris()
data = pd.DataFrame(iris["data"], columns=iris["feature_names"])
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [41]:
## Prevendo com a coluna petal length
X = pd.DataFrame(data['petal length (cm)'],columns=['petal length (cm)'] )
y = pd.DataFrame(iris["target"],columns=['target'])
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(X_train, y_train)  
pred = clf.predict(X_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test, pred))

[[12  0  0]
 [ 0  5  2]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.71      0.83         7
           2       0.85      1.00      0.92        11

    accuracy                           0.93        30
   macro avg       0.95      0.90      0.92        30
weighted avg       0.94      0.93      0.93        30



In [42]:
## Prevendo com a coluna petal length
X = pd.DataFrame(data['petal width (cm)'],columns=['petal width (cm)'] )
y = pd.DataFrame(iris["target"],columns=['target'])
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

clf = MLPClassifier(alpha=0.01,max_iter=2000)
clf.fit(X_train, y_train)  
pred = clf.predict(X_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test, pred))

[[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [43]:
## Testando com outros algoritmos - KNeighborsClassifier
## Prevendo com a coluna petal length

X = pd.DataFrame(data['petal width (cm)'],columns=['petal width (cm)'] )
y = pd.DataFrame(iris["target"],columns=['target'])
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)  
pred = clf.predict(X_test)

print(confusion_matrix(y_test,pred))
print(classification_report(y_test, pred))

[[13  0  0]
 [ 0  9  0]
 [ 0  1  7]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.90      1.00      0.95         9
           2       1.00      0.88      0.93         8

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

